from typing import Any

class NativeSolverError(RuntimeError): ...

class SolverManager:
    def __init__(self, config: dict[str, Any] | None = None) -> None: ...
    def solve(self, solution: object, schema: dict[str, Any]) -> int: ...
    def get_status(self, job_id: int) -> dict[str, object]: ...
    def drain_events(self, job_id: int) -> list[dict[str, object]]: ...
    def snapshot(self, job_id: int, snapshot_revision: int | None = None) -> object: ...
    def pause(self, job_id: int) -> None: ...
    def resume(self, job_id: int) -> None: ...
    def cancel(self, job_id: int) -> None: ...
    def delete(self, job_id: int) -> None: ...

def solve(solution: object, schema: dict[str, Any], config: dict[str, Any] | None = None) -> object: ...
def calculate_score(solution: object, schema: dict[str, Any]) -> object: ...
def init_console() -> None: ...
def validate_schema(schema: dict[str, Any]) -> None: ...
def native_version() -> str: ...
