from typing import Any, TypedDict

class UiAsset(TypedDict):
    path: str
    content_type: str
    cache_control: str
    bytes: bytes

class NativeSolverError(RuntimeError): ...
class CompiledSchema: ...

class QualifiedCandidateTraceProvenance:
    def __init__(
        self,
        *,
        schema_sha256: str,
        instance_sha256: str,
        initial_state_sha256: str,
        core_tree_sha256: str,
        build_sha256: str,
        producer: str,
    ) -> None: ...
    @property
    def schema_sha256(self) -> str: ...
    @property
    def instance_sha256(self) -> str: ...
    @property
    def initial_state_sha256(self) -> str: ...
    @property
    def core_tree_sha256(self) -> str: ...
    @property
    def build_sha256(self) -> str: ...
    @property
    def producer(self) -> str: ...

class SolverManager:
    def __init__(self, config: dict[str, Any] | None = None) -> None: ...
    def _preflight_qualified_candidate_trace_provenance(
        self,
        *,
        qualified_candidate_trace_provenance: (
            QualifiedCandidateTraceProvenance | None
        ) = None,
    ) -> None: ...
    def solve(
        self,
        solution: object,
        schema: CompiledSchema,
        *,
        qualified_candidate_trace_provenance: (
            QualifiedCandidateTraceProvenance | None
        ) = None,
    ) -> int: ...
    def get_status(self, job_id: int) -> dict[str, object]: ...
    def telemetry_detail(self, job_id: int) -> dict[str, object]: ...
    def drain_events(self, job_id: int) -> list[dict[str, object]]: ...
    def snapshot(self, job_id: int, snapshot_revision: int | None = None) -> object: ...
    def pause(self, job_id: int) -> None: ...
    def resume(self, job_id: int) -> None: ...
    def cancel(self, job_id: int) -> None: ...
    def delete(self, job_id: int) -> None: ...

def solve(
    solution: object, schema: CompiledSchema, config: dict[str, Any] | None = None
) -> object: ...
def calculate_score(solution: object, schema: CompiledSchema) -> object: ...
def compile_schema(schema: dict[str, Any]) -> CompiledSchema: ...
def init_console() -> None: ...
def ui_asset(path: str) -> UiAsset | None: ...
def ui_asset_paths() -> list[str]: ...
def validate_schema(schema: dict[str, Any]) -> None: ...
def native_version() -> str: ...
